services:
  stage-db:
    image: mysql:8.0
    container_name: stage-db
    environment:
      MYSQL_ROOT_PASSWORD: pppp
      MYSQL_DATABASE: ppp_stage
    ports:
      - "3307:3306"
    networks:
      - stage-network
    volumes:
      - stage-db-data:/var/lib/mysql

  stage-server:
    image: ameskar/ppp:stage-latest
    environment:
      DATABASE_URL: mysql://root:pppp@stage-db:3306/ppp_stage
      NODE_ENV: stage
      PORT: 8080
    ports:
      - "8081:8080"
    depends_on:
      - stage-db
    networks:
      - stage-network
    restart: unless-stopped

  nginx:
    image: ameskar/nginx-proxy-stage:latest
    container_name: nginx-proxy-stage
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - stage-server
    networks:
      - stage-network

volumes:
  stage-db-data:
    driver: local

networks:
  stage-network:
    driver: bridge
