name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    outputs:
      image-tag: ${{ steps.set-tag.outputs.sha }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set IMAGE_TAG to short commit SHA
        id: set-tag
        run: echo "sha=${GITHUB_SHA::8}" >> $GITHUB_OUTPUT

      - name: Set Docker username environment variable
        run: echo "USERNAME=${{ secrets.DOCKERHUB_USERNAME }}" >> $GITHUB_ENV

      - name: Debug final tags
        run: |
          IMAGE_TAG=${{ steps.set-tag.outputs.sha }}
          echo "Image tag with SHA: $USERNAME/ppp:$IMAGE_TAG"
          echo "Latest tag: $USERNAME/ppp:latest"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ env.USERNAME }}/ppp:${{ steps.set-tag.outputs.sha }}
            ${{ env.USERNAME }}/ppp:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Start ssh-agent and add key
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to EC2 (pull image + run container with docker-compose)
        env:
          IMAGE_TAG: ${{ needs.build-and-push.outputs.image-tag }}
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "\
            echo 'Logging into Docker Hub' && \
            printf '%s' '${{ secrets.DOCKERHUB_TOKEN }}' | docker login -u '${{ secrets.DOCKERHUB_USERNAME }}' --password-stdin && \
            docker-compose -f <(echo \"\
version: '3.9'
services:
  app:
    image: ${{ secrets.DOCKERHUB_USERNAME }}/ppp:${IMAGE_TAG}
    container_name: ppp
    ports:
      - 8080:8080
    restart: always
\") up -d"

