name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - stage
  workflow_dispatch:

jobs:
  # Build and push Docker image
  build-and-push:
    runs-on: ubuntu-latest
    outputs:
      image-tag: ${{ steps.set-tag.outputs.sha }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set IMAGE_TAG to short commit SHA
        id: set-tag
        run: |
          echo "sha=${GITHUB_SHA:0:8}" >> $GITHUB_OUTPUT

      - name: Set Docker username environment variable
        run: echo "USERNAME=${{ secrets.DOCKERHUB_USERNAME }}" >> $GITHUB_ENV

      - name: Debug final tags
        run: |
          IMAGE_TAG=${{ steps.set-tag.outputs.sha }}
          echo "Image tag with SHA: $USERNAME/ppp:$IMAGE_TAG"
          echo "Latest tag: $USERNAME/ppp:latest"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push app Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: |
            ${{ env.USERNAME }}/ppp:latest

      - name: Build and push Production Nginx
        uses: docker/build-push-action@v4
        with:
          context: ./nginx
          file: ./nginx/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/nginx-proxy:latest
      
      - name: Build and push Stage Nginx
        uses: docker/build-push-action@v4
        with:
          context: ./nginx
          file: ./nginx/Dockerfile.stage
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/nginx-stage:latest

  deploy-stage:
    needs: build-and-push
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/stage'
    env:
      SSH_USER: ${{ secrets.STAGE_SSH_USER }}
      SSH_HOST: ${{ secrets.STAGE_SSH_HOST }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      ENV_FILE_CONTENT: ${{ secrets.ENV_FILE_STAGE }}
      IMAGE_TAG: ${{ needs.build-and-push.outputs.image-tag }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Start ssh-agent
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.STAGE_SSH_PRIVATE_KEY }}

      - name: Deploy staging
        run: |
          ssh -o StrictHostKeyChecking=no ${SSH_USER}@${SSH_HOST} "mkdir -p ~/ppp-stage"

          cat docker-compose.stage.yml | ssh -o StrictHostKeyChecking=no ${SSH_USER}@${SSH_HOST} "tee ~/ppp-stage/docker-compose.stage.yml > /dev/null"

          ssh -o StrictHostKeyChecking=no ${SSH_USER}@${SSH_HOST} "echo '${ENV_FILE_CONTENT}' > ~/ppp-stage/.env.stage"

          ssh -o StrictHostKeyChecking=no ${SSH_USER}@${SSH_HOST} "
            echo \$DOCKERHUB_TOKEN | docker login -u \$DOCKERHUB_USERNAME --password-stdin
            docker pull ${DOCKERHUB_USERNAME}/ppp:latest
            docker pull ${DOCKERHUB_USERNAME}/nginx-stage:latest
            docker-compose -f ~/ppp-stage/docker-compose.stage.yml --env-file ~/ppp-stage/.env.stage up -d --force-recreate --remove-orphans
          "

  deploy-production:
    needs: build-and-push
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    env:
      SSH_USER: ${{ secrets.SSH_USER }}
      SSH_HOST: ${{ secrets.SSH_HOST }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      ENV_FILE_CONTENT: ${{ secrets.ENV_FILE_CONTENT }}
      IMAGE_TAG: ${{ needs.build-and-push.outputs.image-tag }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Start ssh-agent
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy production
        run: |
          ssh -o StrictHostKeyChecking=no ${SSH_USER}@${SSH_HOST} "mkdir -p ~/ppp"

          cat docker-compose.yml | ssh -o StrictHostKeyChecking=no ${SSH_USER}@${SSH_HOST} "tee ~/ppp/docker-compose.yml > /dev/null"

          ssh -o StrictHostKeyChecking=no ${SSH_USER}@${SSH_HOST} "echo '${ENV_FILE_CONTENT}' > ~/ppp/.env.production"

          ssh -o StrictHostKeyChecking=no ${SSH_USER}@${SSH_HOST} "
            echo \$DOCKERHUB_TOKEN | docker login -u \$DOCKERHUB_USERNAME --password-stdin
            docker pull ${DOCKERHUB_USERNAME}/ppp:latest
            docker pull ${DOCKERHUB_USERNAME}/nginx-proxy:latest
            docker-compose -f ~/ppp/docker-compose.yml --env-file ~/ppp/.env.production up -d --force-recreate --remove-orphans
          "
