name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    outputs:
      image-tag: ${{ steps.set-tag.outputs.sha }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set IMAGE_TAG to short commit SHA
        id: set-tag
        run: |
          echo "sha=${GITHUB_SHA:0:8}" >> $GITHUB_OUTPUT

      - name: Set Docker username environment variable
        run: echo "USERNAME=${{ secrets.DOCKERHUB_USERNAME }}" >> $GITHUB_ENV

      - name: Debug final tags
        run: |
          IMAGE_TAG=${{ steps.set-tag.outputs.sha }}
          echo "Image tag with SHA: $USERNAME/ppp:$IMAGE_TAG"
          echo "Latest tag: $USERNAME/ppp:latest"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: |
            ${{ env.USERNAME }}/ppp:${{ steps.set-tag.outputs.sha }}
            ${{ env.USERNAME }}/ppp:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    env:
      SSH_USER: ${{ secrets.SSH_USER }}
      SSH_HOST: ${{ secrets.SSH_HOST }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      IMAGE_TAG: ${{ needs.build-and-push.outputs.image-tag }}

    steps:
      - name: Start ssh-agent
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Pull and run containers on EC2
        run: |
          ssh -o StrictHostKeyChecking=no ${SSH_USER}@${SSH_HOST} "
            # Go to project directory
            cd /home/${SSH_USER}/ppp

            # Login to Docker Hub
            echo \$DOCKERHUB_TOKEN | docker login -u \$DOCKERHUB_USERNAME --password-stdin

            # Pull the new server image and recreate containers
            docker-compose pull
            docker-compose up -d --remove-orphans --force-recreate
          "

